export const job = [
  {
    id: 1,
    posisi: "Web Developer",
    kota: "Tegal",
    perusahaan: "PT Honda",
    waktu: "2j",
    gaji: 2000000,
    desc: "Mengembangkan Web dan merancang design pada tampilan UI",
  },
  {
    posisi: "Manager",
    kota: "Jakarta",
    perusahaan: "PT Mayora",
    waktu: "7j",
    gaji: 6000000,
    desc: "Monitoring karyawan dan Menangani tugas-tugas sumber daya manusia dan menjaga hubungan positif dengan karyawan",
    id: 2,
  },
  {
    posisi: "Software Enginer",
    kota: "Jakarta",
    perusahaan: "Tech Innovator",
    waktu: "1j",
    gaji: 9000000,
    desc: "Mengembangkan solusi perangkat lunak inovatif",
    id: 3,
  },
  {
    posisi: "Data Analyst",
    kota: "Surabaya",
    perusahaan: "Data Insight Corp",
    waktu: "9j",
    gaji: 8000000,
    desc: "Menganalisis data untuk menghasilkan wawasan berharga",
    id: 4,
  },
  {
    posisi: "Marketing Coordinator",
    kota: "Bandung",
    perusahaan: "Global Brands Inc",
    waktu: "5j",
    gaji: 5000000,
    desc: "Koordinasi kampanye pemasaran dan acara promosi",
    id: 5,
  },
  {
    posisi: "UX Designer",
    kota: "Yogyakarta",
    perusahaan: "Design Studios Ltd",
    waktu: "1j",
    gaji: 4000000,
    desc: "Merancang pengalaman pengguna yang menariki",
    id: 6,
  },
  {
    posisi: "Financial Analyst",
    kota: "Semarang",
    perusahaan: "Capital Advisors",
    waktu: "2j",
    gaji: 6000000,
    desc: "Menganalisis kinerja keuangan dan memberikan rekomendasi",
    id: 7,
  },
  {
    posisi: "Human Resources Manager",
    kota: "Medan",
    perusahaan: "PeopleFirst Corp",
    waktu: "1j",
    gaji: 7000000,
    desc: "Mengelola kebijakan HR dan strategi pengembangan organisasi",
    id: 8,
  },
  {
    posisi: "Sales Executive",
    kota: "Denpasar",
    perusahaan: "SalesPro Solutions",
    waktu: "19j",
    gaji: 3000000,
    desc: "Mengidentifikasi peluang penjualan dan menjalin hubungan dengan pelanggan",
    id: 9,
  },
  {
    posisi: "Content Writer",
    kota: "Makassar",
    perusahaan: "Creative Words Co",
    waktu: "1j",
    gaji: 5000000,
    desc: "Menghasilkan konten kreatif dengan pesan yang kuat",
    id: 10,
  },
  {
    posisi: "Operations Coordinator",
    kota: "Palembang",
    perusahaan: "Efficiency Solutions",
    waktu: "12j",
    gaji: 6000000,
    desc: "Koordinasi operasional untuk efisiensi maksimal",
    id: 11,
  },
  {
    posisi: "Software Engineer",
    kota: "Jakarta",
    perusahaan: "TechSolutions",
    waktu: "20j",
    gaji: 19000000,
    desc: "Mengembangkan solusi perangkat lunak mutakhir untuk memenuhi kebutuhan teknologi.",
    id: 12,
  },
  {
    posisi: "Marketing Coordinator",
    kota: "Surabaya",
    perusahaan: "GlobalMarket",
    waktu: "1h",
    gaji: 3000000,
    desc: "Membantu dalam kampanye dan strategi pemasaran untuk mencapai target pasar global.",
    id: 13,
  },
  {
    posisi: "Data Analyst",
    kota: "Bandung",
    perusahaan: "DataInsights",
    waktu: "2h",
    gaji: 3000000,
    desc: "Menganalisis pola data dan menghasilkan wawasan berharga untuk pengambilan keputusan",
    id: 14,
  },
  {
    posisi: "Graphic Designer",
    kota: "Bali",
    perusahaan: "CreativeVisions",
    waktu: "2h",
    gaji: 4500000,
    desc: "Menciptakan desain grafis yang menarik secara visual untuk berbagai keperluan kreatif",
    id: 15,
  },
  {
    posisi: "Financial Analyst",
    kota: "Medan",
    perusahaan: "FinanceWorld",
    waktu: "2j",
    gaji: 5400000,
    desc: "Menilai data keuangan dan menyusun laporan yang akurat untuk analisis bisnis",
    id: 16,
  },
  {
    posisi: "Customer Service",
    kota: "Karawang",
    perusahaan: "ServiceCare",
    waktu: "15j",
    gaji: 2300000,
    desc: "Membantu pelanggan dengan pertanyaan dan masalah, serta memastikan kepuasan mereka terpenuhi",
    id: 17,
  },
  {
    posisi: "Product Manager",
    kota: "Yogyakarta",
    perusahaan: "ProductMasters",
    waktu: "11j",
    gaji: 20000000,
    desc: "Mengelola pengembangan produk dan merumuskan strategi pemasaran yang efektif",
    id: 18,
  },
  {
    posisi: "HR Specialist",
    kota: "Semarang",
    perusahaan: "HRPro",
    waktu: "4h",
    gaji: 15000000,
    desc: "Menangani tugas-tugas sumber daya manusia dan menjaga hubungan positif dengan karyawan",
    id: 19,
  },
  {
    posisi: "Sales Executive",
    kota: "Bekasi",
    perusahaan: "SalesGenius",
    waktu: "3j",
    gaji: 5000000,
    desc: "Mempromosikan dan menjual produk perusahaan dengan kemampuan komunikasi yang kuat",
    id: 20,
  },
  {
    posisi: "Content Writer",
    kota: "Tangerang",
    perusahaan: "ContentCreators",
    waktu: "22j",
    gaji: 7000000,
    desc: "Menulis konten yang menarik dan informatif untuk berbagai platform dan tujuan",
    id: 21,
  },
  {
    id: 22,
    posisi: "Content Writer",
    kota: "Tangerang",
    perusahaan: "ContentCreators",
    waktu: "22h",
    gaji: 7000000,
    desc: "Menulis konten menarik dan informatif untuk platform beragam, mencapai target audiens dengan efektif.",
  },
  {
    id: 23,
    posisi: "Insinyur Perangkat Lunak",
    kota: "Jakarta",
    perusahaan: "TechSolutions",
    waktu: "1m",
    gaji: 15000000,
    desc: "Mengembangkan solusi perangkat lunak mutakhir yang mendukung pertumbuhan teknologi dan inovasi.",
  },
  {
    id: 24,
    posisi: "Koordinator Pemasaran",
    kota: "Surabaya",
    perusahaan: "GlobalMarket",
    waktu: "2m",
    gaji: 10000000,
    desc: "Membantu dalam kampanye dan strategi pemasaran, memperluas jangkauan dan pengenalan merek.",
  },
  {
    id: 25,
    posisi: "Analisis Data",
    kota: "Bandung",
    perusahaan: "DataInsights",
    waktu: "3m",
    gaji: 12000000,
    desc: "Menganalisis pola data, mengidentifikasi tren, dan memberikan wawasan berharga untuk pengambilan keputusan.",
  },
  {
    id: 26,
    posisi: "Desainer Grafis",
    kota: "Bali",
    perusahaan: "CreativeVisions",
    waktu: "1b",
    gaji: 9000000,
    desc: "Menciptakan desain grafis menarik, mengkomunikasikan pesan secara visual, dan meningkatkan branding.",
  },
  {
    id: 27,
    posisi: "Analis Keuangan",
    kota: "Medan",
    perusahaan: "FinanceWorld",
    waktu: "2b",
    gaji: 14000000,
    desc: "Menilai data keuangan, menyusun laporan akurat, dan memberikan wawasan penting untuk pengelolaan keuangan.",
  },
  {
    id: 28,
    posisi: "Pramuniaga Layanan Pelanggan",
    kota: "Makassar",
    perusahaan: "ServiceCare",
    waktu: "3b",
    gaji: 8000000,
    desc: "Membantu pelanggan dengan pertanyaan dan masalah, memastikan kepuasan pelanggan tercapai dengan baik.",
  },
  {
    id: 29,
    posisi: "Manajer Produk",
    kota: "Yogyakarta",
    perusahaan: "ProductMasters",
    waktu: "4b",
    gaji: 18000000,
    desc: "Mengelola pengembangan produk, merumuskan strategi, dan memastikan produk sesuai dengan kebutuhan pasar.",
  },
  {
    id: 30,
    posisi: "Spesialis Sumber Daya Manusia",
    kota: "Semarang",
    perusahaan: "HRPro",
    waktu: "5b",
    gaji: 11000000,
    desc: "Menangani tugas-tugas sumber daya manusia, memastikan hubungan positif, dan mengembangkan karyawan.",
  },
  {
    id: 31,
    posisi: "Eksekutif Penjualan",
    kota: "Palembang",
    perusahaan: "SalesGenius",
    waktu: "6b",
    gaji: 9500000,
    desc: "Mempromosikan dan menjual produk perusahaan, membangun hubungan dengan pelanggan, dan mencapai target penjualan.",
  },
];
